In [17]:
print(
"""
@Description: 一些工作中遇见的操作技巧
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-06 22:28:30
"""
)


@Description: 一些工作中遇见的操作技巧
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-06 22:28:30



# 有关于Numpy

In [18]:
import numpy as np

## Check which interval index a value is

In [19]:
values = 10 * np.random.random(size=(15,))
values

array([3.65885441, 2.9016878 , 6.37844471, 7.43488344, 9.8165023 ,
       1.84753143, 8.76369748, 8.64561419, 5.59252007, 9.1315472 ,
       0.58246098, 1.05569338, 0.19551919, 7.2570116 , 8.60358114])

In [20]:
import pandas as pd
scores = [-11, -3, 8, 35, 39, 99]
bins = pd.DataFrame(data={'bin': [[-np.inf, 1.8], [1.8, 2.2], [2.2, 3.7], [3.7, 4.9], [4.9, 9.1], [9.1, np.inf]], 
                          'scores': scores})
bins

bin  scores
0  [-inf, 1.8]     -11
1   [1.8, 2.2]      -3
2   [2.2, 3.7]       8
3   [3.7, 4.9]      35
4   [4.9, 9.1]      39
5   [9.1, inf]      99

In [21]:
interval = np.unique(bins.explode('bin')['bin'])
interval.sort()
interval

array([-inf, 1.8, 2.2, 3.7, 4.9, 9.1, inf], dtype=object)

In [22]:
sample_score = np.searchsorted(interval, values, side='left') - 1
sample_score

array([2, 2, 4, 4, 5, 1, 4, 4, 4, 5, 0, 0, 0, 4, 4], dtype=int64)

In [23]:
bins['scores'].get(sample_score).reset_index(drop=True)

0      8
1      8
2     39
3     39
4     99
5     -3
6     39
7     39
8     39
9     99
10   -11
11   -11
12   -11
13    39
14    39
Name: scores, dtype: int64

## 查找区间和对应的得分

In [24]:
values = pd.Series([-1, 10, 25, 37, 48, 55, 62, 77, 82])
# Define the bin intervals
bins = [-np.inf, 0, 30, 60, 100]

# Categorize the values into bins
categories = pd.DataFrame({'bin':pd.cut(values, bins, right=False).astype(str)})
categories

bin
0    [-inf, 0.0)
1    [0.0, 30.0)
2    [0.0, 30.0)
3   [30.0, 60.0)
4   [30.0, 60.0)
5   [30.0, 60.0)
6  [60.0, 100.0)
7  [60.0, 100.0)
8  [60.0, 100.0)

In [25]:
scores = pd.DataFrame(data={'bin': ['[-inf, 0.0)', '[0.0, 30.0)', '[30.0, 60.0)', '[60.0, 100.0)'],
                            'score': [-7, 8, 11, 19]})
scores

bin  score
0    [-inf, 0.0)     -7
1    [0.0, 30.0)      8
2   [30.0, 60.0)     11
3  [60.0, 100.0)     19

In [26]:
# ✅💕
pd.cut(values, bins, right=False, labels=scores['score']).astype(int)

0    -7
1     8
2     8
3    11
4    11
5    11
6    19
7    19
8    19
dtype: int32

In [27]:
categories.merge(scores, how='left', on='bin')

bin  score
0    [-inf, 0.0)     -7
1    [0.0, 30.0)      8
2    [0.0, 30.0)      8
3   [30.0, 60.0)     11
4   [30.0, 60.0)     11
5   [30.0, 60.0)     11
6  [60.0, 100.0)     19
7  [60.0, 100.0)     19
8  [60.0, 100.0)     19