In [5]:
print(
"""
@Description: 一些工作中遇见的操作技巧
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-06 22:28:30
"""
)


@Description: 一些工作中遇见的操作技巧
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-06 22:28:30



# 有关于Numpy

In [1]:
import numpy as np

## Check which interval index a value is

In [12]:
values = 10 * np.random.random(size=(15,))
values

array([9.26542597, 8.85589798, 8.55501871, 6.7209031 , 0.61752997,
       6.5382497 , 2.12153549, 4.20783383, 5.91670871, 9.02807651,
       0.23750688, 7.47841956, 9.23739258, 6.83249949, 7.92508376])

In [75]:
import pandas as pd
scores = [-11, -3, 8, 35, 39, 99]
bins = pd.DataFrame(data={'bin': [[-np.inf, 1.8], [1.8, 2.2], [2.2, 3.7], [3.7, 4.9], [4.9, 9.1], [9.1, np.inf]], 
                          'scores': scores})
bins

bin  scores
0  [-inf, 1.8]     -11
1   [1.8, 2.2]      -3
2   [2.2, 3.7]       8
3   [3.7, 4.9]      35
4   [4.9, 9.1]      39
5   [9.1, inf]      99

In [77]:
interval = np.unique(bins.explode('bin')['bin'])
interval.sort()
interval

array([-inf, 1.8, 2.2, 3.7, 4.9, 9.1, inf], dtype=object)

In [80]:
sample_score = np.searchsorted(interval, values, side='left') - 1
sample_score

array([5, 4, 4, 4, 0, 4, 1, 3, 4, 4, 0, 4, 5, 4, 4], dtype=int64)

In [81]:
bins['scores'].get(sample_score).reset_index(drop=True)

0     99
1     39
2     39
3     39
4    -11
5     39
6     -3
7     35
8     39
9     39
10   -11
11    39
12    99
13    39
14    39
Name: scores, dtype: int64

## 查找区间和对应的得分

In [82]:
values = pd.Series([-1, 10, 25, 37, 48, 55, 62, 77, 82])
# Define the bin intervals
bins = [-np.inf, 0, 30, 60, 100]

# Categorize the values into bins
categories = pd.DataFrame({'bin':pd.cut(values, bins, right=False).astype(str)})
categories

bin
0    [-inf, 0.0)
1    [0.0, 30.0)
2    [0.0, 30.0)
3   [30.0, 60.0)
4   [30.0, 60.0)
5   [30.0, 60.0)
6  [60.0, 100.0)
7  [60.0, 100.0)
8  [60.0, 100.0)

In [83]:
scores = pd.DataFrame(data={'bin': ['[-inf, 0.0)', '[0.0, 30.0)', '[30.0, 60.0)', '[60.0, 100.0)'],
                            'score': [-7, 8, 11, 19]})
scores

bin  score
0    [-inf, 0.0)     -7
1    [0.0, 30.0)      8
2   [30.0, 60.0)     11
3  [60.0, 100.0)     19

In [84]:
categories.merge(scores, how='left', on='bin')

bin  score
0    [-inf, 0.0)     -7
1    [0.0, 30.0)      8
2    [0.0, 30.0)      8
3   [30.0, 60.0)     11
4   [30.0, 60.0)     11
5   [30.0, 60.0)     11
6  [60.0, 100.0)     19
7  [60.0, 100.0)     19
8  [60.0, 100.0)     19